#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "NGLScene.h"


// Adapted from:
// https://github.com/NCCA/labcode-jmacey-2/tree/main/ParticleQt

QT_BEGIN_NAMESPACE
namespace Ui
{
    class MainWindow;
}
QT_END_NAMESPACE

/// \brief Main application
/// Handles the GUI and embeds the NGL OpenGL scene
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /// \brief Constructor with optional parent widget
    /// \param parent Parent widget, default nullptr
    explicit MainWindow(QWidget *parent = nullptr);

    /// \brief Destructor.
    ~MainWindow();

private:
    Ui::MainWindow *m_ui;    ///< Pointer to UI object generated by Qt Designer
    NGLScene *m_gl;          ///< Pointer to OpenGL rendering widget
};

#endif // MAINWINDOW_H
